{{- if .Values.cosign.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cosign-verify-{{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: cosign-verify
        image: gcr.io/projectsigstore/cosign:v2.6.0
        command:
        - sh
        - -c
        - |
          # Install AWS CLI
          apk add --no-cache aws-cli
          
          # Login to ECR
          aws ecr get-login-password --region us-east-1 | cosign login --username AWS --password-stdin {{ .Values.image.repository | regexFind "^[^/]+" }}
          
          # Verify signature
          cosign verify \
            --attachment-tag-prefix=SIGNATURE- \
            --certificate-identity-regexp={{ .Values.cosign.certificateIdentity }} \
            --certificate-oidc-issuer={{ .Values.cosign.oidcIssuer }} \
            "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
{{- end }}