#t2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
  #namespace: {{ .Values.namespace.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "common.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "common.labels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ include "common.fullname" . }}
          image: "{{ required "image.repository is required" .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ required "image.tag is required when digest is not set" .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ required "image.pullPolicy is required" .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ required "containerPort is required" .Values.containerPort }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "common.fullname" . }}-env