{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ required (printf "Missing value for annotation.%s" $key) $value | quote }}  
    {{- end }}
spec:
  ingressClassName: {{ required "ingress.ingressControllerClassResourceName is required" .Values.ingress.ingressControllerClassResourceName }}
  rules:
    - host: {{ required "ingress.host is required" .Values.ingress.host }}
      http:
        paths:
          - path: {{ required "ingress.ingressPath is required" .Values.ingress.ingressPath}}
            pathType: Prefix
            backend:
              service:
                name: {{ include "common.fullname" . }}
                port:
                  name: http
{{- end }}