{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  {{- if .Values.namespace.annotations }}
  annotations:
    {{- toYaml .Values.namespace.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- end }}