{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- end }}