{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name | default "aws-secretsmanager" }}
  #namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.secretStore.syncWave | default "-1" | quote }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.service | default "SecretsManager" }}
      region: {{ .Values.secretStore.region | default "us-east-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccountName | default "frontend-sa" }}
{{- end }}